apiVersion: app/v1
kind: Deployment
metadata:
  name: fastapi-devops
  labels:
    app: fastapi-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-devops
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: fastapi-devops
    spec:
      containers:
      - name: fastapi-devops
        image: registry.digitalocean.com/devopscontainertje/crypto-api:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-devops-service
spec:
  selector:
    app: app.kubernetes.io/name: fastapi-devops
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

