CREATE TABLE USERS (
	ID int NOT NULL AUTO_INCREMENT,
    GEBRUIKERSNAAM varchar(255) NOT NULL,
    WACHTWOORD varchar(255) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (GEBRUIKERSNAAM)
);

CREATE TABLE CRYPTOCURRENCIES (
	ID int NOT NULL AUTO_INCREMENT,
    AFKORTING varchar(255) NOT NULL,
    NAAM varchar(255) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (AFKORTING)
);

CREATE TABLE TRANSACTIES (
	ID int NOT NULL AUTO_INCREMENT,
    CRYPTOCURRENCY_ID int NOT NULL,
    USER_ID int NOT NULL,
    TRANSACTIE_TIJDSTIP timestamp NOT NULL,
    AANTAL decimal(60,30) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (CRYPTOCURRENCY_ID) REFERENCES CRYPTOCURRENCIES(ID)
);

CREATE TABLE FAVORIETEN (
	ID int NOT NULL AUTO_INCREMENT,
    CRYPTOCURRENCY_ID int NOT NULL,
    USER_ID int NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
	FOREIGN KEY (CRYPTOCURRENCY_ID) REFERENCES CRYPTOCURRENCIES(ID)
);
