name: Build and publish

on:
  push:
    branches:
      - main


jobs:
  build_and_push:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
      - name: Build image 
        run: docker build -t devops/crypto-api \
         --build-arg DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }} \
         --build-arg LIVECOINWATCH_API_KEY=${{ secrets.LIVECOINWATCH_API_KEY }} .
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600
      - name: Tag image 
        run:
          docker tag devops/crypto-api registry.digitalocean.com/devopscontainertje/crypto-api:latest
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/devopscontainertje/crypto-api:latest
